Debug
TelecomParistoc/MotorController pull request #9
Opened 2017-11-05 22:13 UTC by ndeconto

Le robot roule comme il le doit, que penses-tu du code ?

2017-11-06 20:45 UTC, le-roux requested changes

2017-11-06 20:45 UTC, le-roux commented on src/control.c
> +    uint32_t counter = 0U;
Donner un nom plus explicite (il compte quoi?)

2017-11-06 20:45 UTC, le-roux commented on src/control.c
> +        static int cpt = 0;
Même remarque, donner un nom plus explicite

2017-11-06 20:45 UTC, le-roux commented on src/i2c_interface.c
> +  //return *((int32_t *) (&x));
Du code commenté, à retirer

2017-11-06 20:45 UTC, le-roux commented on src/i2c_interface.c
> +        printf("rx_buffer = %x %d %d\n", rx_buffer[0], rx_buffer[1], rx_buffer[2]);
C'était utile pour le debug mais on doit pouvoir l'enlever maintenant

2017-11-06 20:45 UTC, le-roux commented on src/i2c_interface.c
> +            printf("Low goal mean dist received : %d %d\n", rx_buffer[1], rx_buffer[2]);
À retirer également je pense

2017-11-06 20:45 UTC, le-roux commented on src/main.c
> +	dist_command_received = TRUE;
2 lignes à retirer

2017-11-06 20:45 UTC, le-roux commented on src/position.c
> +    if (d == 0.0f) { // no movement
S'il n'y a rien dans le if, autant le retirer

2017-11-06 20:45 UTC, le-roux commented
Comme c'est la première, je vais dire ce que j'aurais fait personnellement. A toi de prendre ce que tu souhaites de ces conseils (en fonction de ton avis sur la question).

J'aurais regroupé en un seul commit les 3 commits suivants:
7b8152b
262d754
f5c9071

Le message de commit "conflict solved" ne me paraît pas clair, d'autant que je vois aucun conflit, juste de l'ajout de code (on dirait un merge d'ailleurs).

Pour les WIP, les retirer va être vraiment complexe donc pour cette fois, on peut les laisser. Mais à l'avenir c'est bien de les retirer.

2017-12-01 18:17 UTC, ndeconto commented
I would like to merge debug into master, but there is a conflict with i2cInterfaceGenerator. I don't understand why, because I didn't touch to this repo. Any idea ?
I don't know if you have time to look at the code... But the tests I've made with libmotors are OK.

2017-12-03 16:19 UTC, le-roux approved these changes

2017-12-03 16:42 UTC, merged